# -*- coding: utf-8 -*-
"""Atomic JSON result writing with provenance. Result files are never edited
by hand; they are always regenerated by rerunning the script that wrote them."""
from __future__ import annotations
import hashlib, json, os, platform, sys, tempfile, time


def versions():
    out = {"python": sys.version.split()[0], "platform": platform.platform()}
    for m in ("numpy", "pandas", "scipy", "sklearn", "xgboost", "tabpfn",
              "torch", "folktables"):
        try:
            out[m] = __import__(m).__version__
        except Exception:
            out[m] = None
    return out


def config_hash(obj):
    return hashlib.sha256(json.dumps(obj, sort_keys=True).encode()).hexdigest()[:16]


def write_json(path, payload):
    payload = dict(payload)
    payload["written_at"] = time.strftime("%Y-%m-%dT%H:%M:%S")
    payload["versions"] = versions()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path), suffix=".tmp")
    with os.fdopen(fd, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=1, allow_nan=True)
    os.replace(tmp, path)
    return path
